name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Install Android & Gluon SDKs
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip wget
          wget https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-22.1.0.1-gluon.tar.gz
          tar -xzf graalvm-svm-linux-22.1.0.1-gluon.tar.gz
          export GRAALVM_HOME=$PWD/graalvm-svm-linux-22.1.0.1-gluon
          export PATH=$GRAALVM_HOME/bin:$PATH
          echo "GRAALVM_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
          echo "$GRAALVM_HOME/bin" >> $GITHUB_PATH

      - name: Native Android build
        run: ./mvnw gluonfx:build gluonfx:package -Pandroid

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: belsign-android-apk
          path: target/gluonfx/host/*.apk
