name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Gluon Plugin (Optional Stub)
        run: |
          mkdir -p ~/.gluon/substrate
          echo "{}" > ~/.gluon/substrate/plugins.json

      - name: Build APK
        run: mvn gluonfx:build gluonfx:package -Pandroid

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: belsign-apk
          path: target/gluonfx/aarch64-android/*.apk
