name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java (used for Maven)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Download Gluon GraalVM CE
        run: |
          wget https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-gluon-22.1.0.1-Final.zip -O graalvm.zip
          unzip -q graalvm.zip -d $HOME
          echo "GRAALVM_HOME=$HOME/graalvm-svm-22.1.0.1-Final" >> $GITHUB_ENV

      - name: Build APK
        run: mvn -Pandroid gluonfx:build gluonfx:package

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: belsign-apk
          path: target/gluonfx/aarch64-android/*.apk
