# .github/workflows/android-build.yml
name: Android APK (Build with Gluon Client)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      # --- adjust if your pom.xml uses a different profile name ---
      GLUON_PROFILE: android-release
      # exact version that matches GluonFX plugin 1.0.28
      GRAAL_VERSION: 22.3.1-gluon
      ANDROID_NDK_VERSION: 23.1.7779620

    steps:
      # 1️⃣  Checkout ----------------------------------------------------------------
      - uses: actions/checkout@v4

      # 2️⃣  JDK 17 (needed for Maven + Gluon) --------------------------------------
      - name: Set up Temurin 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3️⃣  Install Gluon-patched GraalVM + native-image ---------------------------
      - name: Install Gluon GraalVM ${{ env.GRAAL_VERSION }}
        run: |
          curl -L -o gluon-graalvm.zip \
            "https://download.gluonhq.com/substrate/graalvm/graalvm-svm-java17-linux-aarch64-${GRAAL_VERSION}.zip"
          unzip -q gluon-graalvm.zip -d $HOME
          echo "GRAALVM_HOME=$HOME/graalvm-svm-java17-${GRAAL_VERSION}" >> $GITHUB_ENV
          echo "$HOME/graalvm-svm-java17-${GRAAL_VERSION}/bin" >> $GITHUB_PATH

      # 4️⃣  Android SDK + NDK ------------------------------------------------------
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Install Android NDK ${{ env.ANDROID_NDK_VERSION }}
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -O ndk.zip
          unzip -q ndk.zip
          mkdir -p $ANDROID_HOME/ndk
          mv android-ndk-r23b $ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV
          yes | sdkmanager --licenses >/dev/null

      # 5️⃣  Build & Package APK with GluonFX Maven plugin --------------------------
      - name: Build APK
        run: mvn -B gluonfx:build gluonfx:package -P${GLUON_PROFILE}

      # 6️⃣  Upload artifact --------------------------------------------------------
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: belsign-apk
          path: |
            target/gluonfx/*-android/*.apk
